### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by GuiDevloper** [GuiDevloper/nulla#1]
- [x] Add `help`-me action f1db766aae30233db1281f059623e87119ce865b
- Add automatized deploy powers
  - [x] Heroku (ae26bd682a0960d5378aec11d4226fb7c2e0f2cd)
  - [x] Vercel (local: 34efb53a690882177f7dc7a16358ec67116a84ba | CI: 8cc8ba582976e809e7f25c47dfe19aaef1fa0f50)
  - [ ] Github
- [x] Dive into CI powers
- ~~Add automatized generation of config files (e.g `package.json` key -> `vercel.json`)~~
- Think beyond on how the future API _CyberNulla_ looks like

Proposed future API:
`npx nulla`
- `deploy` (build & deploy, default: from local)
  - `vercel`
  - ~~`heroku`~~ (doesn't need `cd` and has problems with `ssg`)
  - `github`
    - `--cd` (continuous deployment mode)
    - `--ssg` (static build)
- `new-ci` (generate files for CI workflow) (created: ae26bd682a0960d5378aec11d4226fb7c2e0f2cd)
  - `heroku` (Procfile) (done: ae26bd682a0960d5378aec11d4226fb7c2e0f2cd)
  - `github`
  - `vercel` (done: ae26bd682a0960d5378aec11d4226fb7c2e0f2cd)
    - `--gitlab` (add files for different CI environments, default: .github/workflows)
    - `--bucket`
- `create`
  - `--template/-t`
- `build` (added support to Nullstack CLI in f54ef46ee76f29df2430450a4b8e7bb4cbb9991e)
  - ~~`--ssg --spa --ssr`~~
- `help`
  - `<command>`
