### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by Mortaro** [GuiDevloper/nulla#2]
Here is a suggested roadmap to make Nulla 1.0 (and Nullstack X:)

Nulla would become a real assistant while Nullstack would be the "magician". Nulla would be a cli containing everything that is helpful but opinionated (for example where to deploy)

- [x] remove `nulla start/build` (leave it to Nullstack so it does not duplicate commands)
- [ ] add `nulla start` as a command to run Nullstack in production mode (could start .production/server or server static assets depending on the use case)
- [x] remove `nulla add` (temporarily), plugins will not be part of Nullstack 1.0  but a revamp on them will be one of the first things to be coded
- [] improve deploy commands (see below)

When using `nulla deploy vercel` it should:

- [ ] ask if the user wants to create a vercel.json and inform that this project is not yet configured for Vercel.
- [ ] ask if the user wants to use ci or cli
- [ ] install vercel cli if needed
- [ ] if project is configured deploy using the chosen method

Supported hosts at 1.0:

- [ ] Heroku
- [ ] Vercel
- [ ] GitHub

Deploy via ftp/ssh would be nice because of Brazilian shared hosts

I would probably change some messages in Nulla cli, and I am not sure if having Portuguese support is needed, as code is normally made in English and the commands are simple. Removing Portuguese would make the codebase easier to contribute to, and also faster to ship. However is we keep Portuguese we should also translate Nullstack cli
